version: '3'

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - main

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - main
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - main

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/gmallet/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/gmallet/sgoinfre/wordpress
      o: bind

networks:
  main:
    driver: bridge
