#!/usr/bin/env bash

MARIADB_DATABASE=weweland
MARIADB_USER=wewe
MARIADB_PWD=wewe
MARIADB_ROOT_PWD=root

mariadb << EOF
CREATE DATABASE IF NOT EXISTS $MARIADB_DATABASE;
CREATE USER IF NOT EXISTS $MARIADB_USER@localhost IDENTIFIED BY $MARIADB_PWD;
GRANT ALL PRIVILEGES ON $MARIADB_DATABASE.* TO $MARIADB_USER@localhost IDENTIFIED BY $MARIADB_PWD;
ALTER USER root@localhost IDENTIFIED BY $MARIADB_ROOT_PWD;
FLUSH PRIVILEGES;
EOF

